# required properties
group = com.almostreliable
modId = summoningrituals
modName = Summoning Rituals
modVersion = 3.0.0
minecraftVersion = 1.21.1
neoforgeVersion = 21.1.71

# replacement properties
modAuthor = Almost Reliable
modDescription = Create custom summoning rituals for items, mobs, and commands.
modCredits = Requested by Saereth from FTB. Altar model and textures by mo_shark. Recipe viewer textures by Ne0kys.
license = All Rights Reserved
githubUser = AlmostReliable
githubRepo = summoningrituals

# mod dependencies
kjsVersion = 2101.7.1-build.181

# settings
neoForge.parchment.minecraftVersion = 1.21.1
neoForge.parchment.mappingsVersion = 2024.11.17
almostgradle.buildconfig.name = ModConstants
almostgradle.launchArgs.autoWorldJoin = true
almostgradle.recipeViewers.jei.runConfig = true
almostgradle.recipeViewers.jei.version = 19.22.1.316
almostgradle.recipeViewers.jei.mode = API

# gradle
org.gradle.vfs.watch = true
org.gradle.configuration-cache = true
org.gradle.parallel = true
