# Project
group = com.almostreliable.mods
license = GNU Lesser General Public License v3.0

# Minecraft
minecraftVersion = 1.20.1

# Mod
modVersion = 2.0.8
modPackage = com.almostreliable.summoningrituals
modId = summoningrituals
modName = Summoning Rituals
modAuthor = Almost Reliable
modDescription = Create custom summoning rituals for items and mobs.
modCredits = Requested by Saereth from FTB. Altar model and textures by mo_shark. Recipe viewer textures by Ne0kys.

# Project Dependencies
neoForge.parchment.minecraftVersion = 1.20.1
neoForge.parchment.mappingsVersion = 2023.09.03

# Forge Dependencies
# don't update this, Forge is broken afterward
forgeVersion = 47.1.3
forgeRecipeViewer = jei

# Mod Dependencies
jeiVersion = 15.2.0.25
reiVersion = 12.0.634
kubeVersion = 2001.6.4-build.95

# Github
githubUser = AlmostReliable
githubRepo = summoningrituals

# Gradle
org.gradle.vfs.watch = true
org.gradle.configuration-cache = true
org.gradle.parallel = true
