modLoader = "javafml"
loaderVersion = "[${forgeLoaderVersion},)"
issueTrackerURL = "https://github.com/${githubUser}/${githubRepo}/issues"
license = "${license}"

[[mods]]
modId = "${modId}"
version = "${version}"
displayName = "${modName}"
credits = "${modCredits}"
authors = "${modAuthor}"
description = '''${modDescription}'''

[[dependencies.${modId}]]
modId = "forge"
mandatory = true
versionRange = "[${forgeVersion},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${modId}]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraftVersion},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${modId}]]
modId = "jei"
mandatory = false
versionRange = "[${jeiVersion},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${modId}]]
modId = "roughlyenoughitems"
mandatory = false
versionRange = "[${reiVersion},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${modId}]]
modId = "kubejs"
mandatory = false
versionRange = "[${kubeVersion},)"
ordering = "AFTER"
side = "BOTH"
