@ParametersAreNonnullByDefault @MethodsReturnNonnullByDefault
package com.almostreliable.summoningrituals.compat.kubejs;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
