@ParametersAreNonnullByDefault @MethodsReturnNonnullByDefault
package com.almostreliable.summoningrituals.recipe;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
