@ParametersAreNonnullByDefault @MethodsReturnNonnullByDefault
package com.almostreliable.summoningrituals.compat.jei.blockingredient;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
