@ParametersAreNonnullByDefault @MethodsReturnNonnullByDefault
package com.almostreliable.summoningrituals.network;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
