@ParametersAreNonnullByDefault @MethodsReturnNonnullByDefault
package com.almostreliable.summoningrituals.util;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
